from __future__ import annotations

import argparse

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="neuroseed")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("list-envs")
    p.add_argument("--split", choices=["all", "train", "test"], default="all")

    p = sub.add_parser("eval-env")
    p.add_argument("env_name")
    p.add_argument("--agent", choices=["random", "heuristic", "gated"], default="heuristic")
    p.add_argument("--predictor", choices=["noop", "symbolic"], default="symbolic")
    p.add_argument("--episodes", type=int, default=3)
    p.add_argument("--db")

    p = sub.add_parser("eval-suite")
    p.add_argument("--split", choices=["all", "train", "test"], default="test")
    p.add_argument("--episodes", type=int, default=2)
    p.add_argument("--agent", choices=["heuristic", "gated"], default="gated")
    p.add_argument("--predictor", choices=["noop", "symbolic"], default="symbolic")
    p.add_argument("--db")

    p = sub.add_parser("run-suite")
    p.add_argument("--split", choices=["all", "train", "test"], default="test")
    p.add_argument("--episodes", type=int, default=2)
    p.add_argument("--agent", choices=["heuristic", "gated"], default="gated")
    p.add_argument("--predictor", choices=["noop", "symbolic"], default="symbolic")
    p.add_argument("--db", default="data/suite.db")

    p = sub.add_parser("collect-dataset")
    p.add_argument("--split", choices=["all", "train", "test"], default="all")
    p.add_argument("--episodes", type=int, default=10)
    p.add_argument("--agents", nargs="+", choices=["random", "heuristic", "gated"], default=["random", "heuristic", "gated"])
    p.add_argument("--predictor", choices=["noop", "symbolic"], default="symbolic")
    p.add_argument("--db", default="data/model_ready.db")
    p.add_argument("--replay-out", default="data/model_ready/replay.jsonl")
    p.add_argument("--features-out", default="data/model_ready/features.jsonl")

    p = sub.add_parser("collect-counterfactual-dataset")
    p.add_argument("--split", choices=["all", "train", "test"], default="all")
    p.add_argument("--episodes", type=int, default=20)
    p.add_argument("--agents", nargs="+", choices=["random", "heuristic", "gated"], default=["random", "heuristic", "gated"])
    p.add_argument("--counterfactual-out", default="data/model_ready/counterfactual.jsonl")
    p.add_argument("--features-out", default="data/model_ready/features.jsonl")
    p.add_argument("--no-rollouts", action="store_true")
    p.add_argument("--no-variants", action="store_true")
    p.add_argument("--lock-code-lengths", type=int, nargs="+", default=[3, 4])
    p.add_argument("--curriculum-profile", choices=["legacy", "slot_v2", "slot_model_needed_v1", "slot_model_needed_v2", "slot_model_needed_v3"], default="legacy")
    p.add_argument("--curriculum-target-groups-per-family", type=int, default=4_000)

    p = sub.add_parser("validate-counterfactual")
    p.add_argument("path")

    p = sub.add_parser("run-lock")
    p.add_argument("--agent", choices=["random", "heuristic", "gated"], default="gated")
    p.add_argument("--predictor", choices=["noop", "symbolic"], default="symbolic")
    p.add_argument("--episodes", type=int, default=1)
    p.add_argument("--db", default="data/episodes.db")

    p = sub.add_parser("export-replay")
    p.add_argument("--db", default="data/episodes.db")
    p.add_argument("--out", default="data/replay/events.jsonl")

    p = sub.add_parser("validate-replay")
    p.add_argument("path")

    p = sub.add_parser("inspect-replay")
    p.add_argument("path")

    p = sub.add_parser("export-runtime-replay")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--out", default="data/model_ready/runtime_replay.jsonl")
    p.add_argument("--limit", type=int)

    p = sub.add_parser("run-runtime-replay-etl")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--out", default="data/model_ready/runtime_replay.jsonl")
    p.add_argument("--limit", type=int)
    p.add_argument("--min-rows", type=int, default=1)
    p.add_argument("--allow-no-execution", action="store_true")

    p = sub.add_parser("validate-runtime-replay")
    p.add_argument("path")

    p = sub.add_parser("check-runtime-replay-gates")
    p.add_argument("path")
    p.add_argument("--min-rows", type=int, default=1)
    p.add_argument("--allow-no-execution", action="store_true")

    p = sub.add_parser("export-runtime-features")
    p.add_argument("runtime_replay_path")
    p.add_argument("--out", default="data/model_ready/runtime_features.jsonl")
    p.add_argument("--test-ratio", type=float, default=0.2)

    p = sub.add_parser("validate-runtime-features")
    p.add_argument("path")

    p = sub.add_parser("check-runtime-feature-gates")
    p.add_argument("path")
    p.add_argument("--min-rows", type=int, default=10)
    p.add_argument("--min-actions", type=int, default=1)

    p = sub.add_parser("train-runtime-action-model")
    p.add_argument("--features", default="data/model_ready/runtime_features.jsonl")
    p.add_argument("--out", default="artifacts/runtime_action_model.pt")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--hidden-dim", type=int, default=64)
    p.add_argument("--hidden-layers", type=int, default=2)
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")
    p.add_argument("--patience", type=int, default=20)
    p.add_argument("--min-rows", type=int, default=10)
    p.add_argument("--min-actions", type=int, default=1)

    p = sub.add_parser("eval-runtime-action-model")
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--features", default="data/model_ready/runtime_features.jsonl")
    p.add_argument("--split", choices=["train", "test", "all"], default="test")
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")

    p = sub.add_parser("export-features")
    p.add_argument("replay_path")
    p.add_argument("--out", default="data/replay/features.jsonl")

    p = sub.add_parser("validate-features")
    p.add_argument("path")

    p = sub.add_parser("inspect-slot-features")
    p.add_argument("path")

    p = sub.add_parser("export-slot-features")
    p.add_argument("counterfactual_path")
    p.add_argument("--out", default="data/model_ready/features_slot.jsonl")

    p = sub.add_parser("validate-slot-features")
    p.add_argument("path")

    p = sub.add_parser("merge-slot-features")
    p.add_argument("paths", nargs="+")
    p.add_argument("--out", required=True)

    p = sub.add_parser("audit-slot-dataset")
    p.add_argument("path")

    p = sub.add_parser("audit-maze-grounding")
    p.add_argument("path")
    p.add_argument("--limit", type=int, default=20)

    p = sub.add_parser("check-slot-dataset-gates")
    p.add_argument("path")
    p.add_argument("--lock-max-ratio", type=float, default=0.60)
    p.add_argument("--maze-min-ratio", type=float, default=0.15)
    p.add_argument("--tool-min-ratio", type=float, default=0.15)
    p.add_argument("--hiddenish-min-ratio", type=float, default=0.25)
    p.add_argument("--information-gain-group-min-ratio", type=float, default=0.08)
    p.add_argument("--post-reveal-group-min-ratio", type=float, default=0.08)
    p.add_argument("--post-setup-execution-group-min-ratio", type=float, default=0.03)
    p.add_argument("--post-setup-positive-group-min-ratio", type=float, default=0.02)
    p.add_argument("--post-setup-correct-action-group-min-ratio", type=float, default=0.02)

    p = sub.add_parser("export-balanced-slot-dataset")
    p.add_argument("path")
    p.add_argument("--out", default="data/model_ready/features_slot_balanced_v1.jsonl")
    p.add_argument("--target-rows", type=int, default=120_000)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--drop-heldout", action="store_true")

    p = sub.add_parser("train-world-model")
    p.add_argument("--features", required=True)
    p.add_argument("--out", default="artifacts/world_model.pt")
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--hidden-dim", type=int, default=64)
    p.add_argument("--hidden-layers", type=int, default=2)
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")
    p.add_argument("--patience", type=int, default=60)

    p = sub.add_parser("eval-world-model")
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--features", required=True)
    p.add_argument("--split", choices=["train", "test", "all"], default="test")
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")

    p = sub.add_parser("eval-action-ranking")
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--features", required=True)
    p.add_argument("--split", choices=["train", "test", "all"], default="test")
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")

    p = sub.add_parser("export-world-model-onnx")
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--out", default="artifacts/world_model.onnx")
    p.add_argument("--no-verify", action="store_true")
    p.add_argument("--static-batch", action="store_true")

    p = sub.add_parser("run-training-pipeline")
    p.add_argument("--features", required=True)
    p.add_argument("--out-dir", default="artifacts/training_runs")
    p.add_argument("--run-name")
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=1024)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--hidden-dim", type=int, default=64)
    p.add_argument("--hidden-layers", type=int, default=2)
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")
    p.add_argument("--patience", type=int, default=10)
    p.add_argument("--split", choices=["train", "test", "all"], default="test")
    p.add_argument("--no-onnx-verify", action="store_true")
    p.add_argument("--static-batch", action="store_true")
    p.add_argument("--skip-gate-ablation", action="store_true")
    p.add_argument("--gate-ablation-episodes", type=int, default=50)
    p.add_argument("--trace-episodes", type=int, default=10)
    p.add_argument("--max-failures-per-env", type=int, default=10)
    p.add_argument("--strict", action="store_true")
    p.add_argument("--allow-gate-failure", action="store_true")
    p.add_argument("--allow-benchmark-failure", action="store_true")
    p.add_argument("--overwrite", action="store_true")

    p = sub.add_parser(
        "train-deploy-model",
        description="Train a world model on this machine and deploy it to Orange Pi as a versioned, non-overwriting release.",
    )
    p.add_argument("run_name_arg", nargs="?", metavar="RUN_NAME", help="new model release name, e.g. slot_v2_mn_v3_004")
    p.add_argument("--features", help="feature JSONL path; defaults to NEUROKERNEL_TRAIN_FEATURES")
    p.add_argument("--out-dir", help="local training run root; defaults to NEUROKERNEL_TRAIN_RUN_DIR")
    p.add_argument("--run-name", help=argparse.SUPPRESS)
    p.add_argument("--remote-host", help="SSH host; defaults to NEUROKERNEL_EDGE_HOST or orangepi5")
    p.add_argument("--remote-project", help="remote project path; defaults to NEUROKERNEL_EDGE_PROJECT")
    p.add_argument("--activate", action="store_true", help="update current model pointer after release deploy")
    p.add_argument("--dry-run", action="store_true", help="preflight local paths and remote release name without training")
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=1024)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--hidden-dim", type=int, default=64)
    p.add_argument("--hidden-layers", type=int, default=2)
    p.add_argument("--device", choices=["auto", "cpu", "cuda"], default="cuda")
    p.add_argument("--patience", type=int, default=10)
    p.add_argument("--split", choices=["train", "test", "all"], default="test")
    p.add_argument("--no-onnx-verify", action="store_true")
    p.add_argument("--static-batch", action="store_true")
    p.add_argument("--skip-gate-ablation", action="store_true")
    p.add_argument("--gate-ablation-episodes", type=int, default=50)
    p.add_argument("--trace-episodes", type=int, default=10)
    p.add_argument("--max-failures-per-env", type=int, default=10)
    p.add_argument("--no-strict", dest="strict", action="store_false")
    p.set_defaults(strict=True)
    p.add_argument("--allow-gate-failure", action="store_true")
    p.add_argument("--allow-benchmark-failure", action="store_true")
    p.add_argument("--overwrite-local-run", action="store_true")
    p.add_argument("--ssh-connect-timeout", type=int, default=10)

    p = sub.add_parser("eval-learned-gate")
    p.add_argument("--model", required=True)
    p.add_argument("--split", choices=["all", "train", "test"], default="test")
    p.add_argument("--episodes", type=int, default=2)
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid")
    p.add_argument("--db")

    p = sub.add_parser("debug-lock-candidates")
    p.add_argument("--env", choices=["lock.train", "lock.test"], default="lock.test")
    p.add_argument("--model")
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid")

    p = sub.add_parser("freeze-baseline")
    p.add_argument("--baseline-name", default="v3.1_first_full_success")
    p.add_argument("--artifacts-dir", default="artifacts")
    p.add_argument("--data-dir", default="data")
    p.add_argument("--out-dir", default="baselines")
    p.add_argument("--evaluation")
    p.add_argument("--artifact-prefix", default="world_model")
    p.add_argument("--training-device", default="cuda")
    p.add_argument("--edge-runtime", default="orangepi5_onnxruntime")
    p.add_argument("--notes")
    p.add_argument("--overwrite", action="store_true")

    p = sub.add_parser("eval-hard-heldout")
    p.add_argument("--model", required=True)
    p.add_argument("--episodes", type=int, default=5)
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid")
    p.add_argument("--out")

    p = sub.add_parser("trace-hard-failures")
    p.add_argument("--model", required=True)
    p.add_argument("--groups", nargs="+", default=["hard_length_heldout", "partial_hidden_smoke"])
    p.add_argument("--episodes", type=int, default=3)
    p.add_argument("--max-failures-per-env", type=int, default=2)
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid")
    p.add_argument("--out")

    p = sub.add_parser("debug-model-needed-failures")
    p.add_argument("--model", required=True)
    p.add_argument("--envs", nargs="+", default=["lock.probe.trap.1", "maze.probe.hazard.green", "maze.probe.hazard.red"])
    p.add_argument("--episodes", type=int, default=1)
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid_veto")
    p.add_argument("--out")

    p = sub.add_parser("run-benchmark")
    p.add_argument("--model", required=True)
    p.add_argument("--out-dir", default="artifacts/benchmark")
    p.add_argument("--episodes", type=int, default=5)
    p.add_argument("--trace-episodes", type=int, default=3)
    p.add_argument("--max-failures-per-env", type=int, default=3)
    p.add_argument("--gate-mode", choices=["model_only", "prior_only", "hybrid", "hybrid_veto"], default="hybrid")
    p.add_argument("--strict", action="store_true")

    p = sub.add_parser("run-gate-ablation")
    p.add_argument("--model", required=True)
    p.add_argument("--out-dir", default="artifacts/benchmark/gate_ablation_v4_4")
    p.add_argument("--episodes", type=int, default=50)
    p.add_argument("--trace-episodes", type=int, default=10)
    p.add_argument("--max-failures-per-env", type=int, default=10)
    p.add_argument("--strict", action="store_true")

    p = sub.add_parser("benchmark-runtime")
    p.add_argument("--model", required=True)
    p.add_argument("--backend", choices=["onnx_cpu", "rknn_npu"], default="onnx_cpu")
    p.add_argument("--iterations", type=int, default=2_000)
    p.add_argument("--samples", type=int, default=256)
    p.add_argument("--batches", type=int, nargs="+", default=[1, 8, 32, 128])
    p.add_argument("--out")

    p = sub.add_parser("harness-actions")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("validate-action-registry")
    p.add_argument("path")

    p = sub.add_parser("harness-status")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("harness-create-task")
    p.add_argument("--task-json")
    p.add_argument("--task-file")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("harness-dry-run")
    p.add_argument("task_id")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("harness-run")
    p.add_argument("task_id")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("harness-approve")
    p.add_argument("task_id")
    p.add_argument("--approved-by", default="cli")
    p.add_argument("--reason")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("harness-reject")
    p.add_argument("task_id")
    p.add_argument("--rejected-by", default="cli")
    p.add_argument("--reason")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("activate-work-item")
    p.add_argument("work_id")
    p.add_argument("--actor", default="cli")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("serve-core-api")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")

    p = sub.add_parser("serve-discord-bot")
    p.add_argument("--core-url")
    p.add_argument("--channel-id", type=int)
    p.add_argument("--token-env", default="DISCORD_BOT_TOKEN")
    p.add_argument("--prefix")
    p.add_argument("--allow-dms", action="store_true", default=None)
    p.add_argument("--allowed-user-id", type=int, action="append")
    p.add_argument("--reply-without-prefix", action="store_true", default=None)
    p.add_argument("--auto-do-low-risk", action="store_true", default=None)

    p = sub.add_parser("serve-work-worker")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")
    p.add_argument("--worker-id")
    p.add_argument("--queues", nargs="+", default=["self_patch", "external_work"])
    p.add_argument("--block-ms", type=int, default=0)
    p.add_argument("--once", action="store_true")

    p = sub.add_parser("harness-improvements")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")
    p.add_argument("--min-gap-count", type=int, default=2)
    p.add_argument("--lookback", type=int, default=200)
    p.add_argument("--propose", action="store_true")

    p = sub.add_parser("serve-improvement-watchdog")
    p.add_argument("--db", default="data/harness.db")
    p.add_argument("--project-root", default=".")
    p.add_argument("--interval-seconds", type=float, default=120.0)
    p.add_argument("--min-gap-count", type=int, default=2)
    p.add_argument("--lookback", type=int, default=200)
    p.add_argument("--once", action="store_true")

    p = sub.add_parser("language-to-core")
    p.add_argument("text")

    p = sub.add_parser("language-to-human")
    p.add_argument("--core-result-json")
    p.add_argument("--core-result-file")
    return parser


